### ISSUE TITLE
typo in license file

### ISSUE THREAD

**Issue by raffaelj** [piotr-cz/cockpit-sql-driver#4]
https://github.com/piotr-cz/cockpit-sql-driver/blob/master/LICENSE#L3

`https://piocz.cz` should be `https://piotr.cz`

**Comment by piotr-cz** [comment]
Thanks, fixed in https://github.com/piotr-cz/cockpit-sql-driver/commit/a1818a9f7235a8743f79b98e785201e8ce48aef3
