### ISSUE TITLE
default bootstrap prioritiy should be higher than 1

### ISSUE THREAD

**Issue by raffaelj** [piotr-cz/cockpit-sql-driver#5]
I'm not sure, if it was intentional, but the default bootstrap priority should be very high (e. g. 9999) to change the driver with the highest priority.

A simple test in `addons/test/bootstrap.php`:

```php
// default priority 0
$this->on('cockpit.bootstrap', function() {
    $test = $this->storage->getKey('cockpit/options', 'multiplane', []);
    var_dump($test); // array(0) { } 
});

// priority 10
$this->on('cockpit.bootstrap', function() {
    $test = $this->storage->getKey('cockpit/options', 'multiplane', []);
    var_dump($test); // Call to a member function findOne() on null
}, 10);
```

If I set `'bootstrapPriority' => 9999` in the database options, the event with prio 10 works.

**Comment by piotr-cz** [comment]
You are right, higher priority means event will be triggered sooner.
What do you think about setting default value to `PHP_INT_MAX` ?

**Comment by piotr-cz** [comment]
Or `PHP_INT_MAX / 2` so there is still some door open of other events.
I should also describe the `bootstrapPriority` option in readme

**Comment by raffaelj** [comment]
`PHP_INT_MAX` and `PHP_INT_MAX / 2` would be unpredictable. It differs on 32bit and 64bit systems and it's hard to remember. And there might be use cases when I want to trigger that event before the SqlDriver fired. You never know...

So the decision is kind of random. I would choose a number, that is high enough for most use cases, e. g. 9999 or 3306.

**Comment by piotr-cz** [comment]
My assumption was that this option would be changed by user which decides on addons priorities and by default it should be highest number.

Anyway set default bootstrap priority to `999` in https://github.com/piotr-cz/cockpit-sql-driver/commit/6f93d7d4fdd6caf4cae0d79074a783ac5078c5bc.

Thanks!
