### ISSUE TITLE
feature request: table prefix

### ISSUE THREAD

**Issue by raffaelj** [piotr-cz/cockpit-sql-driver#6]
Tables are created on the fly and this can mess things up.

Simple test:
```php
$this->on('cockpit.bootstrap', function() {
    $test = $this->storage->getKey('test', 'test', []);
});
```
Now my database has a new table named "test".

Another test with an existing table:
```php
$this->on('cockpit.bootstrap', function() {
    $test = $this->storage->getKey('wp_users', 'test', []);
});
```

result:
```
PDOException while running query
SELECT
"document"
FROM
`wp_users`
WHERE JSON_UNQUOTE(JSON_EXTRACT(`document`, '$.\"key\"')) = 'test'
LIMIT 1
```

The current behaviour makes it impossible to use the same database with a different application or with custom tables in it.

If I could prefix all cockpit tables with e. g. `cp_`, I could still create a ton of useles tables on the fly with a typo in my storage request, but it wouldn't hurt much.

**Comment by piotr-cz** [comment]
Was there a `wp_users` table in your database before running second query?


As for creating tables on the fly

I've decided to [create collection tables](https://github.com/piotr-cz/cockpit-sql-driver/blob/v1.0.0-rc.2/lib/MongoSql/Collection.php#L78) on the fly, because it's cleaner and at first seemed cheaper than in every method (find/ insert/ delete/ count).

My assumption was that if developer decides to operate on collection/ table, he/ she is sure it exists.

Probably this could be refactored with a cached _table exists_ check on every read type operation and _create table_ on write type,

**Comment by raffaelj** [comment]
> Was there a wp_users table in your database before running second query?

Yes. I tested it with a WordPress installation in the same database. I know, it's better to use different hosts and databases per app, but people do such things. Especially in the WordPress world with the cheapest web hoster possible, where a second database costs extra money.

Well, ... and I'm working on a Cockpit implementation as a WordPress plugin...

> My assumption was that if developer decides to operate on collection/ table, he/ she is sure it exists.

If we ignore typos and tests with wrong methods while getting started with Cockpit, there is still the possibility, that a different addon author uses a table name, that exists already in my database. A table prefix would eliminate these conflicts.

> Probably this could be refactored with a cached table exists check on every read type operation and create table on write type,

That sounds nice, but I think, it behaves like the SQLite driver right now. If I remember correctly, that one creates empty tables on read requests on the fly, too.

**Comment by piotr-cz** [comment]
I'll prepare table prefix feature and let's leave table checks for other time as it's separate issue

**Comment by piotr-cz** [comment]
Could you test feature in #7?

**Comment by raffaelj** [comment]
It seems, like nothing has changed. I guess, you have to add the prefix to the query builder, too.

**Comment by raffaelj** [comment]
Sorry, my fault. I renamed the old SqlDriver module instead of deleting it and copied the fork, so it was loaded before the replacemant fired. Stupid mistake :D

So it seems to work with the prefix.
After creating a test entry in a test collection, I have these new databases:

```
cp_cockpit/accounts
cp_cockpit/options
cp_cockpit/revisions
cp_collections/test
```

And this one created a new table `cp_test`:

```php
$this->on('cockpit.bootstrap', function() {
    $test = $this->storage->getKey('test', 'test', []);
    var_dump($test); // array(0) { } 
});
```
 Thank you very much for that fast fix.

**Comment by raffaelj** [comment]
After some more tests, it looks very promising. I added an asset and a singleton via Cockpit UI, I sent a message with a contact form from the WordPress frontend and it was successfully stored. Now my database looks much cleaner than before.

![screenshot_wp_cp_sql-driver](https://user-images.githubusercontent.com/13042193/89518142-ccfa0080-d7da-11ea-8adc-fe8c3cd4330b.png)

**Comment by piotr-cz** [comment]
Let's continue thread on on #7
